services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    T3\Vici\:
        resource: '../Classes/*'
        exclude:
            - '../Classes/Domain/Model/*'

    T3\Vici\UserFunction\ItemsProcFunc\:
        resource: '../Classes/UserFunction/ItemsProcFunc/*'
        public: true

    T3\Vici\Generator\TcaManager:
        public: true

    T3\Vici\Repository\ViciRepository:
        public: true
        lazy: true

    T3\Vici\Generator\ProxyClassLoader:
        public: true
