services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    T3\Vici\:
        resource: '../Classes/*'
        exclude:
            - '../Classes/Domain/Model/*'

    T3\Vici\UserFunction\ItemsProcFunc\:
        resource: '../Classes/UserFunction/ItemsProcFunc/*'
        public: true

    T3\Vici\UserFunction\PreviewRenderer\:
        resource: '../Classes/UserFunction/PreviewRenderer/*'
        public: true

    T3\Vici\UserFunction\DisplayCondition\:
        resource: '../Classes/UserFunction/DisplayCondition/*'
        public: true

    T3\Vici\Generator\Extbase\ModelClassNameResolver:
        public: true

    T3\Vici\Repository\ViciRepository:
        public: true
        lazy: true

    T3\Vici\Generator\ProxyClassLoader:
        public: true

    T3\Vici\Localization\ViciParser:
        public: true
