name: my-ext
type: php
docroot: ""
no_project_mount: true
php_version: "8.2"
composer_version: "2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
    - docs.my-ext
    - v11.my-ext
    - v12.my-ext
    - v13.my-ext
additional_fqdns: []
use_dns_when_possible: true
